# Generated by Django 4.0.5 on 2022-06-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='desctiption',
            new_name='description',
        ),
    ]
