# Generated by Django 4.0.5 on 2022-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_rename_desctiption_picture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo_file',
            field=models.ImageField(upload_to='pictures', verbose_name='Изображение'),
        ),
    ]
