# Generated by Django 4.0.5 on 2022-06-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_first_name_alter_author_last_name'),
        ('category', '0001_initial'),
        ('picture', '0005_alter_picture_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
