# Generated by Django 4.0.5 on 2022-07-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(default=1, verbose_name='О авторе'),
            preserve_default=False,
        ),
    ]
