# Generated by Django 4.0.5 on 2022-07-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='about',
            new_name='bio',
        ),
    ]
