# Generated by Django 4.0.5 on 2022-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='albums/covers/placeholder.webp', upload_to='albums/covers', verbose_name='Обложка'),
        ),
    ]
