# Generated by Django 4.0.5 on 2022-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_picture_photo_file'),
        ('album', '0003_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, default='albums/covers/placeholder.webp', upload_to='albums/covers', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ManyToManyField(blank=True, to='picture.picture', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='Новый альбом', max_length=255, verbose_name='Название'),
        ),
    ]
